### ISSUE TITLE
No transparency

### ISSUE THREAD

**Issue by Raze4284** [1882COYS/1882-dots#3]
Visual Studio Code after installing dots dont have transparency
![image](https://github.com/1882COYS/1882-dots/assets/38469989/ea7809c8-2c68-4e01-8b2f-51ff48f778e5)

**Comment by HeikoWasTaken** [comment]
Hey, not sure if you've found a fix by now but this happens because there is no configuration for Visual Studio Code in this repo's hyprland config files. This isn't a bug, just that @1882COYS likely doesn't use vscode, therefore didn't customize anything for it. You can add transparency yourself via [hyprland's window rules](https://wiki.hyprland.org/Configuring/Window-Rules/), so adding something like this: `windowrulev2 = opacity 0.75 override, title:Visual Studio Code, class:Code` into your hyprland.conf should do the trick.

**Comment by lwilk0** [comment]
Hi, I do not use code so this doesn’t apply to the dot files. Thank you for the input. If you were to use the ide I use (vscodium) it should work fine, so there is no issue in the dotfiles.
